import type { Config } from "tailwindcss";
const { fontFamily } = require("tailwindcss/defaultTheme");

const config = {
	darkMode: ["class"],
	content: [
		"./pages/**/*.{ts,tsx}",
		"./components/**/*.{ts,tsx}",
		"./app/**/*.{ts,tsx}",
		"./src/**/*.{ts,tsx}",
	],
	prefix: "",
	theme: {
		container: {
			center: true,
			padding: "2rem",
			screens: {
				"2xl": "1400px",
			},
		},
		extend: {
			fontFamily: {
				sans: ["var(--font-sans)", ...fontFamily.sans], // Inter
				heading: ["var(--font-heading)", ...fontFamily.sans], // Montserrat
			},
			colors: {
				border: "hsl(var(--border))",
				input: "hsl(var(--input))",
				ring: "hsl(var(--ring))",
				background: "hsl(var(--background))",
				foreground: "hsl(var(--foreground))",
				primary: {
					DEFAULT: "hsl(var(--primary))",
					foreground: "hsl(var(--primary-foreground))",
					50: "hsl(var(--primary-50))",
					100: "hsl(var(--primary-100))",
					200: "hsl(var(--primary-200))",
					300: "hsl(var(--primary-300))",
					400: "hsl(var(--primary-400))",
					500: "hsl(var(--primary-500))",
					600: "hsl(var(--primary-600))",
					700: "hsl(var(--primary-700))",
					800: "hsl(var(--primary-800))",
					900: "hsl(var(--primary-900))",
					950: "hsl(var(--primary-950))",
				},
				secondary: {
					DEFAULT: "hsl(var(--secondary))",
					foreground: "hsl(var(--secondary-foreground))",
					50: "hsl(var(--secondary-50))",
					100: "hsl(var(--secondary-100))",
					200: "hsl(var(--secondary-200))",
					300: "hsl(var(--secondary-300))",
					400: "hsl(var(--secondary-400))",
					500: "hsl(var(--secondary-500))",
					600: "hsl(var(--secondary-600))",
					700: "hsl(var(--secondary-700))",
					800: "hsl(var(--secondary-800))",
					900: "hsl(var(--secondary-900))",
					950: "hsl(var(--secondary-950))",
				},
				neutral: {
					50: "hsl(var(--neutral-50))",
					100: "hsl(var(--neutral-100))",
					200: "hsl(var(--neutral-200))",
					300: "hsl(var(--neutral-300))",
					400: "hsl(var(--neutral-400))",
					500: "hsl(var(--neutral-500))",
					600: "hsl(var(--neutral-600))",
					700: "hsl(var(--neutral-700))",
					800: "hsl(var(--neutral-800))",
					900: "hsl(var(--neutral-900))",
					950: "hsl(var(--neutral-950))",
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive))",
					foreground: "hsl(var(--destructive-foreground))",
				},
				success: "hsl(var(--success))",
				warning: "hsl(var(--warning))",
				error: "hsl(var(--error))",
				info: "hsl(var(--info))",
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				accent: {
					DEFAULT: "hsl(var(--accent))",
					foreground: "hsl(var(--accent-foreground))",
				},
				popover: {
					DEFAULT: "hsl(var(--popover))",
					foreground: "hsl(var(--popover-foreground))",
				},
				card: {
					DEFAULT: "hsl(var(--card))",
					foreground: "hsl(var(--card-foreground))",
				},
			},
			borderRadius: {
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)",
			},
			fontSize: {
				// Fluid typography scale - use with font-heading for headings
				"display": ["var(--font-size-display)", {
					lineHeight: "var(--line-height-display)",
					letterSpacing: "var(--letter-spacing-display)",
					fontWeight: "var(--font-weight-display)",
				}],
				"h1": ["var(--font-size-h1)", {
					lineHeight: "var(--line-height-h1)",
					letterSpacing: "var(--letter-spacing-h1)",
					fontWeight: "var(--font-weight-h1)",
				}],
				"h2": ["var(--font-size-h2)", {
					lineHeight: "var(--line-height-h2)",
					letterSpacing: "var(--letter-spacing-h2)",
					fontWeight: "var(--font-weight-h2)",
				}],
				"h3": ["var(--font-size-h3)", {
					lineHeight: "var(--line-height-h3)",
					letterSpacing: "var(--letter-spacing-h3)",
					fontWeight: "var(--font-weight-h3)",
				}],
				"h4": ["var(--font-size-h4)", {
					lineHeight: "var(--line-height-h4)",
					letterSpacing: "var(--letter-spacing-h4)",
					fontWeight: "var(--font-weight-h4)",
				}],
				"h5": ["var(--font-size-h5)", {
					lineHeight: "var(--line-height-h5)",
					letterSpacing: "var(--letter-spacing-h5)",
					fontWeight: "var(--font-weight-h5)",
				}],
				"h6": ["var(--font-size-h6)", {
					lineHeight: "var(--line-height-h6)",
					letterSpacing: "var(--letter-spacing-h6)",
					fontWeight: "var(--font-weight-h6)",
				}],
				"body-lg": ["var(--font-size-body-lg)", {
					lineHeight: "var(--line-height-body-lg)",
					letterSpacing: "var(--letter-spacing-body-lg)",
					fontWeight: "var(--font-weight-body-lg)",
				}],
				"body": ["var(--font-size-body)", {
					lineHeight: "var(--line-height-body)",
					letterSpacing: "var(--letter-spacing-body)",
					fontWeight: "var(--font-weight-body)",
				}],
				"body-sm": ["var(--font-size-body-sm)", {
					lineHeight: "var(--line-height-body-sm)",
					letterSpacing: "var(--letter-spacing-body-sm)",
					fontWeight: "var(--font-weight-body-sm)",
				}],
				"caption": ["var(--font-size-caption)", {
					lineHeight: "var(--line-height-caption)",
					letterSpacing: "var(--letter-spacing-caption)",
					fontWeight: "var(--font-weight-caption)",
				}],
				"caption-sm": ["var(--font-size-caption-sm)", {
					lineHeight: "var(--line-height-caption-sm)",
					letterSpacing: "var(--letter-spacing-caption-sm)",
					fontWeight: "var(--font-weight-caption-sm)",
				}],
				"overline": ["var(--font-size-overline)", {
					lineHeight: "var(--line-height-overline)",
					letterSpacing: "var(--letter-spacing-overline)",
					fontWeight: "var(--font-weight-overline)",
				}],
				"button": ["var(--font-size-button)", {
					lineHeight: "var(--line-height-button)",
					letterSpacing: "var(--letter-spacing-button)",
					fontWeight: "var(--font-weight-button)",
				}],
				"button-sm": ["var(--font-size-button-sm)", {
					lineHeight: "var(--line-height-button-sm)",
					letterSpacing: "var(--letter-spacing-button-sm)",
					fontWeight: "var(--font-weight-button-sm)",
				}],
				"price": ["var(--font-size-price)", {
					lineHeight: "var(--line-height-price)",
					letterSpacing: "var(--letter-spacing-price)",
					fontWeight: "var(--font-weight-price)",
				}],
				"price-sm": ["var(--font-size-price-sm)", {
					lineHeight: "var(--line-height-price-sm)",
					letterSpacing: "var(--letter-spacing-price-sm)",
					fontWeight: "var(--font-weight-price-sm)",
				}],
			},
			spacing: {
				// Fluid spacing scale
				"section": "var(--section-padding-y)",
				"section-sm": "var(--section-padding-y-sm)",
				"section-lg": "var(--section-padding-y-lg)",
				"content": "var(--content-padding)",
				"content-gap": "var(--content-gap)",
				"card": "var(--card-padding)",
				"card-sm": "var(--card-padding-sm)",
				"card-lg": "var(--card-padding-lg)",
				"card-gap": "var(--card-gap)",
				"grid": "var(--grid-gap)",
				"grid-sm": "var(--grid-gap-sm)",
				"grid-lg": "var(--grid-gap-lg)",
				"stack": "var(--stack-gap)",
				"stack-sm": "var(--stack-gap-sm)",
				"stack-lg": "var(--stack-gap-lg)",
				"inline": "var(--inline-gap)",
				"inline-sm": "var(--inline-gap-sm)",
				"inline-lg": "var(--inline-gap-lg)",
				"page": "var(--page-padding-x)",
				"header": "var(--header-height)",
				"sidebar": "var(--sidebar-width)",
				"modal": "var(--modal-padding)",
				"button-x": "var(--button-padding-x)",
				"button-y": "var(--button-padding-y)",
				"input-x": "var(--input-padding-x)",
				"input-y": "var(--input-padding-y)",
				"nav": "var(--nav-item-padding-x)",
				"icon": "var(--icon-gap)",
			},
			maxWidth: {
				"prose": "var(--max-width-prose)",
				"content-xs": "var(--max-width-xs)",
				"content-sm": "var(--max-width-sm)",
				"content-md": "var(--max-width-md)",
				"content-lg": "var(--max-width-lg)",
				"content-xl": "var(--max-width-xl)",
				"content-2xl": "var(--max-width-2xl)",
				"content-3xl": "var(--max-width-3xl)",
				"content-4xl": "var(--max-width-4xl)",
				"content-5xl": "var(--max-width-5xl)",
				"content-6xl": "var(--max-width-6xl)",
				"content-7xl": "var(--max-width-7xl)",
				"container": "var(--container-max-width)",
			},
			gap: {
				"grid": "var(--grid-gap)",
				"grid-sm": "var(--grid-gap-sm)",
				"grid-lg": "var(--grid-gap-lg)",
				"stack": "var(--stack-gap)",
				"stack-sm": "var(--stack-gap-sm)",
				"stack-lg": "var(--stack-gap-lg)",
				"inline": "var(--inline-gap)",
				"inline-sm": "var(--inline-gap-sm)",
				"inline-lg": "var(--inline-gap-lg)",
				"card": "var(--card-gap)",
				"product": "var(--product-card-gap)",
			},
			keyframes: {
				"accordion-down": {
					from: { height: "0" },
					to: { height: "var(--radix-accordion-content-height)" },
				},
				"accordion-up": {
					from: { height: "var(--radix-accordion-content-height)" },
					to: { height: "0" },
				},
			},
			animation: {
				"accordion-down": "accordion-down 0.2s ease-out",
				"accordion-up": "accordion-up 0.2s ease-out",
			},
		},
	},
	plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;

export default config;
